"""Cookie injection for authenticated Tumblr sessions.

The Tumblr Scanner pipeline scrapes mature-flagged blogs. These require an
authenticated session. Rather than requiring manual login per Chrome restart,
we extract session cookies from a browser that is already logged in (one-time),
cache them as JSON, and inject them into fresh Chrome instances via CDP.

Cookie file: cache/tumblr-cookies.json (generated by extract_cookies.py)
Cookie lifetime: ~12 months (Tumblr sid expires ~Aug 2027). Re-extract when
login_wall=True persists after injection.
"""

from __future__ import annotations

import json
import logging
import urllib.request
import urllib.error

from config import CACHE_DIR, CDP_PORT

logger = logging.getLogger("cookie-inject")

COOKIE_CACHE_PATH = CACHE_DIR / "tumblr-cookies.json"


def _get_ws_url(port: int) -> str | None:
    """Get the Browser-level WebSocket URL for a Chrome instance.
    
    Returns None if Chrome is not ready or CDP endpoint unavailable.
    """
    try:
        req = urllib.request.Request(
            f"http://127.0.0.1:{port}/json/version",
            headers={"Accept": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            info = json.loads(resp.read())
            return info.get("webSocketDebuggerUrl")
    except (urllib.error.URLError, urllib.error.HTTPError, OSError, json.JSONDecodeError) as exc:
        logger.debug("CDP endpoint on port %d not ready: %s", port, exc)
        return None


def inject_cookies(port: int | None = None) -> bool:
    """Inject cached Tumblr session cookies into Chrome via CDP.

    Returns True if cookies were injected successfully.
    Call this AFTER Chrome launch, BEFORE starting workers.
    """
    if port is None:
        port = CDP_PORT
    
    if not COOKIE_CACHE_PATH.exists():
        logger.warning("No cached cookies at %s — Chrome will start unauthenticated", COOKIE_CACHE_PATH)
        return False
    
    try:
        cookies = json.loads(COOKIE_CACHE_PATH.read_text())
    except Exception as exc:
        logger.warning("Failed to read cookie cache: %s", exc)
        return False
    
    ws_url = _get_ws_url(port)
    if not ws_url:
        logger.warning("Cannot inject cookies — Chrome WebSocket not available on port %d", port)
        return False
    
    import asyncio
    import websockets
    
    async def _inject():
        async with websockets.connect(ws_url, open_timeout=5) as ws:
            # Enable Network domain first
            await ws.send(json.dumps({"id": 1, "method": "Network.enable", "params": {}}))
            await ws.recv()
            
            # Set each cookie
            for i, cookie in enumerate(cookies, start=2):
                params = {
                    "name": cookie["name"],
                    "value": cookie["value"],
                    "domain": cookie.get("domain", ".tumblr.com"),
                    "path": cookie.get("path", "/"),
                    "httpOnly": cookie.get("httpOnly", False),
                    "secure": cookie.get("secure", False),
                }
                if cookie.get("expires", 0) > 0:
                    params["expires"] = cookie["expires"]
                if cookie.get("sameSite"):
                    params["sameSite"] = cookie["sameSite"]
                
                await ws.send(json.dumps({
                    "id": i,
                    "method": "Network.setCookie",
                    "params": params
                }))
                await ws.recv()
            
            return len(cookies)
    
    try:
        # Use a fresh event loop for async operations
        loop = asyncio.new_event_loop()
        try:
            count = loop.run_until_complete(_inject())
        finally:
            loop.close()
        logger.info("Injected %d Tumblr session cookies into Chrome on port %d", count, port)
        return True
    except Exception as exc:
        logger.warning("Cookie injection failed: %s", exc)
        return False


if __name__ == "__main__":
    # Test injection: python cookie_inject.py [PORT]
    import sys
    port = int(sys.argv[1]) if len(sys.argv) > 1 else CDP_PORT
    import sys as _sys
    _sys.path.insert(0, str(COOKIE_CACHE_PATH.parent.parent))
    success = inject_cookies(port)
    print(f"Cookie injection {'succeeded' if success else 'failed'}")
    sys.exit(0 if success else 1)
